//Authentication Types
export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST"
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS"
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE"
export const LOGOUT = "LOGOUT"
export const RETURN_EMAIL_ERROR_MESSAGE = "RETURN_EMAIL_ERROR_MESSAGE"
export const RETURN_PASSWORD_ERROR_MESSAGE = "RETURN_PASSWORD_ERROR_MESSAGE"